<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNiGtobi\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNiGtobi/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNiGtobi.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNiGtobi\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNiGtobi\appAppKernelProdContainer([
    'container.build_hash' => 'NiGtobi',
    'container.build_id' => '37d89c82',
    'container.build_time' => 1709713033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNiGtobi');
