<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsTic3P\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsTic3P/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBsTic3P.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBsTic3P\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBsTic3P\appAppKernelProdContainer([
    'container.build_hash' => 'BsTic3P',
    'container.build_id' => '8f26f366',
    'container.build_time' => 1709640529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsTic3P');
